valid_size: 50
benchmark: harmbench
attacker_model: ${ATTACKER_ENDPOINT}
defender_model: ${LLAMA2_ENDPOINT}
classifier_model: ${CLASSIFIER_ENDPOINT}
meta_agent_model: gpt-5-2025-08-07
n_repeat: 1
debug_max: 5
max_workers: 16
shuffle_seed: ${SEED}
