valid_size: 50
benchmark: harmbench
attacker_model: ${ATTACKER_ENDPOINTS}
defender_model: ${LLAMA2_ENDPOINT}
classifier_model: ${CLASSIFIER_ENDPOINT}
meta_agent_model: gpt-5-2025-08-07
n_repeat: 1
debug_max: 5
max_workers: 16
shuffle_seed: ${SEED}
expr_name: redteam_gpt-5-2025-08-07_Mistral-7B-Instruct-v0.3_Llama-2-7b-chat-hf_2_diversity_threshold_0.2
diversity_threshold: 0.2
